### ISSUE TITLE
Unable to run ./ml_ops.sh. Java -Xms heap size

### ISSUE THREAD

**Issue by vaisham92** [Open-Network-Insight/open-network-insight#105]
Hi,

I am trying to install the apache spot in a cloudera vm. When I try to run the command "./ml_ops.sh 20161012 flow 1e-10 20", I am getting the following errors. As you can see, I have set the Java options for heap size, still I am unable to process further.

[vaisham@quickstart oni-ml]$ export _JAVA_OPTIONS=-Xms512M
[vaisham@quickstart oni-ml]$ ./ml_ops.sh 20161012 flow 1e-10 20
Picked up _JAVA_OPTIONS: -Xms512M
Picked up _JAVA_OPTIONS: -Xms512M
Picked up _JAVA_OPTIONS: -Xms512M
Invalid initial heap size: -Xms--conf
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

real	0m0.134s
user	0m0.082s
sys	0m0.051s
Picked up _JAVA_OPTIONS: -Xms512M
getmerge: `/user/vaisham/flow/scored_results/20161012/scores/part-*': No such file or directory
[vaisham@quickstart oni-ml]$ 

Thanks,
Vaisham.

**Comment by natedogs911** [comment]
Hello @vaisham92, 
what are the specs of the system you are running this on?
my guess would be that for the quick start vm (assuming that is what you are using) 512m could be too large.
If i remember right they set some low limits in the vm.

I would also suggest that you check the oni.conf/spot.conf and tune the SPK_EXEC and
SPK_EXEC_MEM values, the defaults are likely too high but i don't think it's related to the error you are seeing.

**Comment by vaisham92** [comment]
@natedogs911,

I am running a cloudera VM on VMware. It was allocated 7 GB RAM and 2 cores. 

Thanks.

**Comment by thealy** [comment]
I am getting a very similar response on my newly installed Spot. The ML root machine is a dedicated Linux box with 8 cores and 64 GB memory. I am searching to find where this value is read, since the "Invalid initial heap size: -Xms--conf" looks like a syntax error. But so far I cannot find it.

[spot@hd56:~/ml]# export _JAVA_OPTIONS=-Xms512M
[spot@hd56:~/ml]# ./ml_ops.sh 20161313 flow 1e-10 200
Picked up _JAVA_OPTIONS: -Xms512M
Picked up _JAVA_OPTIONS: -Xms512M
Picked up _JAVA_OPTIONS: -Xms512M
Invalid initial heap size: -Xms--conf
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

real	0m0.483s
user	0m0.296s
sys	0m0.161s
Picked up _JAVA_OPTIONS: -Xms512M
getmerge: `/user/spot/flow/scored_results/20161313/scores/part-*': No such file or directory

I

**Comment by natedogs911** [comment]
i think i see what's going on, 
take a look at this document:
https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ml/SPARKCONF.md

and make sure these values are configured in the spot.conf

I think we need to review the spark conf values in the spark-submit command
https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ml/ml_ops.sh#L87
i think some checks need to be present in the bash script to remove the values if not populated in the spot.conf

**Comment by rabarona** [comment]
Hi @thealy, @vaisham92 

Have you tried without `export _JAVA_OPTIONS=-Xms512M`? 
If you are also getting an error without it, can you please share the logs?

**Comment by thealy** [comment]
Hi @rabarona Here you go. It did not report "Picked up...", but still failed:
[spot@hd56:~/ml]# unset _JAVA_OPTIONS
[spot@hd56:~/ml]# env |grep -i java
JAVA_HOME=/usr/java/jdk1.7.0_13
[spot@hd56:~/ml]# ./ml_ops.sh 20161313 flow 
Invalid initial heap size: -Xms--conf
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

real	0m0.473s
user	0m0.317s
sys	0m0.148s
getmerge: `/user/spot/flow/scored_results/20161313/scores/part-*': No such file or directory

Were there any system logs you need?

**Comment by rabarona** [comment]
So if you check ml_ops.sh you will see there are some extra Java options for executors and driver. I'm not sure what's happening here but from the error looks like -Xms is overlapping with one of the spark properties determined by `--conf`.

In order for me to do deeper research, I'll need OS version, Spark version, Java version (only @vaisham) and if possible a copy of ml_ops.sh.

Thanks for reporting this issue.

**Comment by natedogs911** [comment]
@rabarona this could also be related to whats in the spot.conf

Can you post the relevant fields of the conf file?
also what version of the code you are using (master branch or spot?)

it looks like some of the --conf fields are left empty and it's combining fields.

you can try running bash with -x to see whats actually happening:
`bash -x ./ml_ops.sh 20161313 flow`

**Comment by rabarona** [comment]
You'r are right @natedogs911 
These properties in ml_ops.sh are expected to take values from spot.conf/duxbay.conf (depending on the version you are running).

`--driver-memory ${SPK_DRIVER_MEM} \
  --conf spark.driver.maxResultSize=${SPK_DRIVER_MAX_RESULTS} \
  --conf spark.dynamicAllocation.maxExecutors=${SPK_EXEC} \
  --conf spark.executor.cores=${SPK_EXEC_CORES} \
  --conf spark.executor.memory=${SPK_EXEC_MEM} \
  --conf spark.yarn.driver.memoryOverhead=${SPK_DRIVER_MEM_OVERHEAD} \
  --conf spark.yarn.executor.memoryOverhead=${SPAK_EXEC_MEM_OVERHEAD} target/scala-2.10/oni-ml-assembly-1.1.jar \`

**Comment by thealy** [comment]
I tried to follow the explanation here: https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ml/SPARKCONF.md but got a bit lost. I also think I'm going to need a lot more memory for each of my ML nodes - they have only 8GB. So I cut the values way down, and it still exploded. So I commented all out except SPK_EXEC='8' and TOL='1e-6', and it went back to the earlier error:

Invalid initial heap size: -Xms--conf
Error: Could not create the Java Virtual Machine.

**Comment by rabarona** [comment]
Oh I see, that's the reason why you are getting this error. You need to set values for these properties:

**Comment by thealy** [comment]
I pulled some values out of thin air to try again, and the job says it is running, but not much visible on the nodes. Here are the values, and below that the parsed result using bash-x.

SPK_EXEC='8'
SPK_EXEC_MEM='4000m'
SPK_DRIVER_MEM='4000m'
SPK_DRIVER_MAX_RESULTS='4g'
SPK_EXEC_CORES='4'
SPK_DRIVER_MEM_OVERHEAD='2048'
SPAK_EXEC_MEM_OVERHEAD='2048'
TOL='1e-6'

+ /opt/mapr/spark/spark-1.6.1/bin/spark-submit --class org.opennetworkinsight.SuspiciousConnects --master yarn-client --driver-memory 4000m --conf spark.driver.maxResultSize=4g --conf spark.driver.maxPermSize=512m --conf spark.driver.cores=1 --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.minExecutors=1 --conf spark.dynamicAllocation.maxExecutors=8 --conf spark.executor.cores=4 --conf spark.executor.memory=4000m --conf 'spark.executor.extraJavaOptions=-XX:MaxPermSize=512M -XX:PermSize=512M' --conf spark.shuffle.io.preferDirectBufs=false --conf spark.kryoserializer.buffer.max=512m --conf spark.shuffle.service.enabled=true --conf spark.yarn.am.waitTime=1000000 --conf spark.yarn.driver.memoryOverhead=2048 --conf spark.yarn.executor.memoryOverhead=2048 target/scala-2.10/oni-ml-assembly-1.1.jar --analysis flow --input /user/spot/flow/hive/y=2016/m=10/d=13/ --dupfactor 1000 --feedback /home/spot/ml/flow/20161013/flow_scores.csv --model /home/spot/ml/flow/20161013/model.dat --topicdoc /home/spot/ml/flow/20161013/final.gamma --topicword /home/spot/ml/flow/20161013/final.beta --lpath /home/spot/ml/flow/20161013 --ldapath /home/spot/ml/oni-lda-c --luser /home/spot --mpicmd mpiexec --proccount 45 --topiccount 20 --nodes hd56,hd23,hd24,hd25,hd26,hd27,hd28,hd29,hd30 --scored /user/spot/flow/scored_results/20161013/scores --threshold 1e-6 --maxresults -1

spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
spark.driver.cores is set but does not apply in client mode.

It has been running for 8 minutes. I suspect I made the arguments too small, but I have to learn more about the YARN specs and how they relate to the machines I have. I hope this helps.

**Comment by natedogs911** [comment]
thanks for the reply,

let us know what happens.
Spark/Yarn tuning is it's own science and takes a lot of time.
I have definitely not mastered it yet :)

@vaisham92  let us know if this helps you as well.

**Comment by thealy** [comment]
Still working on it. I decided to make a copy of ml_ops.sh called th_ml_ops.sh below so that I could experiment with arguments and leave the original alone. By removing most of the --conf statements, I got it to run and complete several stages - 14 jobs on the Spark console. Then it stopped and prompted me for the spot user password, ???? - but I entered the password and the result is below. The first time this happened, I added execute permissions for the whole sub-directory (they were already set at the first level at least).

Can anyone shed light on what may be going on here?

Thanks

[spot@hd56:~/ml]# chmod -R a+x oni-lda-c/
[spot@hd56:~/ml]# bash th_ml_ops.sh 20161013 flow 
spot@hd56's password:                                                           
Connection closed by 192.168.4.60
spot@hd56's password: 
spot@hd30's password: 
spot@hd30's password: 
Exception in thread "Thread-87" java.io.IOException: Cannot run program "mpiexec" (in directory "/home/spot/ml/oni-lda-c"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:68)
	at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:132)
	at scala.sys.process.ProcessImpl$CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:93)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:22)
Caused by: java.io.IOException: error=13, Permission denied

**Comment by natedogs911** [comment]
the password prompt is likely because passwordless SSH is not setup between the master ML node and the DataNodes.
it is copying the model.dat to each node, then trying to call mpi from the oni-lda-c folder.
did you build lda and run install_ml.sh prior to this?

**Comment by thealy** [comment]
OK, I fixed the passwordless SSH issue and got much further along with the modified ml_op.sh script. But still hitting the mpiexec permission error:

[spot@hd56:~/ml]# ./th_ml_ops.sh 20161013 flow
Exception in thread "Thread-84" java.io.IOException: Cannot run program "mpiexec" (in directory "/home/spot/ml/oni-lda-c"): error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:68)
        at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:132)

**Comment by vaisham92** [comment]
Can someone give me the minimum configuration of each of the server nodes? I was running these server components in a VM inside my computer. I now have access to multi-node machines and would like to know the minimum requirements of the same. 

[https://github.com/Open-Network-Insight/open-network-insight/wiki/Deployment%20Guide](url)

The link above doesn't mention anything about it.

Thanks.

**Comment by moy8011** [comment]
hi @vaisham92  
It all depends on the dataset you want to test. How large it is?, this will give you an idea of how many Terabytes you need in your cluster.
In the same line, CPU Requirements could go from 12 to 48 or more cores. 64GB in RAM per node could be an starting point but it could go up to 256 GB. 
Consider than Impala and Spark consume tons of RAM.

**Comment by vaisham92** [comment]
I just want to test the happy path. It's not going to be a full-scale deployment for an organization(not yet). Based on the info I collect from this happy path testing, I will probably have to do a full-scale deployment.

So, I need configuration for happy path flow and also for a full-scale deployment.

**Comment by rajeshpatil1** [comment]
Hi I was getting similar kind of error, but after setting export SPARK_DIST_CLASSPATH=$(hadoop classpath)
and export _JAVA_OPTIONS=-Xms120m that error was gone. But a new error is there now as below

root@worker:/home/cloudera/oni-ml# ./ml_ops.sh 20150401 dns 1e-12
Picked up _JAVA_OPTIONS: -Xms120m
Picked up _JAVA_OPTIONS: -Xms120m
Picked up _JAVA_OPTIONS: -Xms120m
Picked up _JAVA_OPTIONS: -Xms120m
16/12/12 20:51:08 INFO Remoting: Starting remoting
16/12/12 20:51:09 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@172.27.3.213:49019]
16/12/12 20:51:09 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkDriverActorSystem@172.27.3.213:49019]
spark.yarn.driver.memoryOverhead is set but does not apply in client mode.
spark.driver.cores is set but does not apply in client mode.
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at org.apache.spark.SparkConf$$anonfun$getInt$2.apply(SparkConf.scala:322)
        at org.apache.spark.SparkConf$$anonfun$getInt$2.apply(SparkConf.scala:322)
        at scala.Option.map(Option.scala:145)
        at org.apache.spark.SparkConf.getInt(SparkConf.scala:322)
        at org.apache.spark.deploy.yarn.ClientArguments.<init>(ClientArguments.scala:67)
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:54)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:157)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:542)
        at org.opennetworkinsight.SuspiciousConnects$.main(SuspiciousConnects.scala:41)
        at org.opennetworkinsight.SuspiciousConnects.main(SuspiciousConnects.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

real    0m2.891s
user    0m5.556s
sys     0m0.212s


any idea how to fix it ?

**Comment by natedogs911** [comment]
Hello @rajeshpatil1 

based on the error i would assume that the spot.conf is missing some spark configuration values,
make sure that lines [37-44](https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-setup/spot.conf#L37) of the spot.conf are filled out.

you could try a base approach with everything set very low and scale up from there:
SPK_EXEC='4'
SPK_EXEC_MEM='2048m'
SPK_DRIVER_MEM='4096m'
SPK_DRIVER_MAX_RESULTS='4g'
SPK_EXEC_CORES='2'
SPK_DRIVER_MEM_OVERHEAD='1536'
SPAK_EXEC_MEM_OVERHEAD='1536'
TOL='1e-6'

You should review [this section](https://github.com/Open-Network-Insight/open-network-insight/blob/spot/spot-ml/SPARKCONF.md#configuring-spots-usage-of-spark) of the SPARKCONF.md file. the above settings may even be too large if you are running a small VM. this is very specific to your cluster setup.
