### ISSUE TITLE
Problem running ml_ops.sh

### ISSUE THREAD

**Issue by jpferrero** [Open-Network-Insight/open-network-insight#181]
Hello,

I'm having an issue with ml_ops.sh:

> ./ml_ops.sh 20170530 dns
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrameReader.parquet(Lscala/collection/Seq;)Lorg/apache/spark/sql/DataFrame;
        at org.opennetworkinsight.dns.DNSPreLDA$.dnsPreLDA(DNSPreLDA.scala:91)
        at org.opennetworkinsight.dns.DNSSuspiciousConnects$.run(DNSSuspiciousConnects.scala:18)
        at org.opennetworkinsight.SuspiciousConnects$.main(SuspiciousConnects.scala:47)
        at org.opennetworkinsight.SuspiciousConnects.main(SuspiciousConnects.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Maybe is a version problem? I'm using Hadoop 2.7, Spark 2.0.0 (and tried with 2.1)

Thanks,

**Comment by jpferrero** [comment]
Solved, it's necessary Spark 1.6
